services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: transfermate              
      POSTGRES_PASSWORD: transfermatepassword      
      POSTGRES_DB: TodoDb            
    ports:
      - "5432:5432"                      
  todowebapitransfermate:
    image: todowebapitransfermate
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TODOAPI_DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
